### ISSUE TITLE
Badger::Codecs fails to compile

### ISSUE THREAD

**Issue by puck** [abw/Badger#21]
Hey,

Badger::Codecs fails to compile with Perl v5.36:

```
puck@dirk:~/personal/RT/debian/Badger$ perl -Ilib -c lib/Badger/Codecs.pm 
Bareword "CHAINED" not allowed while "strict subs" in use at lib/Badger/Codecs.pm line 60.
BEGIN not safe after errors--compilation aborted at lib/Badger/Codecs.pm line 139.
Compilation failed in require at lib/Badger/Codec/Chain.pm line 15.
BEGIN failed--compilation aborted at lib/Badger/Codec/Chain.pm line 15.
Compilation failed in require at lib/Badger/Codecs.pm line 16.
BEGIN failed--compilation aborted at lib/Badger/Codecs.pm line 16.
```

The test cases all pass though.
